{{- range $es := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $es.name }}
spec:
  refreshInterval: {{ $es.refreshInterval }}
  secretStoreRef:
    name: {{ $es.secretStoreRefName }}
    kind: {{ $es.secretStoreRefKind | default "ClusterSecretStore" }}
  target:
    name: {{ $es.targetName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ $es.dataKey }}
{{- end }}
